### ISSUE TITLE
Website blocked by ESET Nod32

### ISSUE THREAD

**Issue by emileber** [i18next/i18next.com#12]
This is what I see when I visit [i18next.com](http://i18next.com/):
![2016-10-26 11_31_39-alert - eset endpoint antivirus](https://cloud.githubusercontent.com/assets/3286135/19732768/d87df12e-9b6f-11e6-8b93-de80912a9b0b.png)

On [virustotal.com](https://virustotal.com/en/url/4ea36db5393ea552bbe040f58fd0e56afe24513e5cb1a2bc21f3ed46f1f82519/analysis/), ESET is the sole antivirus who blocks `i18next.com`. So it's probably a false positive.

To request unblocking the website, follow the following instruction:
http://support.eset.com/kb141/#SubmitWebsite

I'm not affiliated with ESET, I'm just a victim of the false positive.

**Comment by emileber** [comment]
I sent an email myself to samples@eset.com

**Comment by emileber** [comment]
I received:

> Dear Emile Bergeron, 
> 
> Thank you for your submission. 
> The site will be unblocked in the next update. 
> 
> Regards, 
> 
> ESET Malware Response Team

**Comment by jamuhl** [comment]
great...thank you

**Comment by emileber** [comment]
That's a pleasure, it was also a pain for myself.

The new update is already out and it works for me, I'm closing this!
