### ISSUE TITLE
Recommendation: Library of Project Structures

### ISSUE THREAD

**Issue by ghost** [i18next/i18next.com#13]
When I used i18next and the various plugins that are used, I found that there was a lack of documentation which addressed how you would best maintain a cross-platform language bundle and where those bundles should be included. It might be advantageous to create a single page which shows an example of how a single language bundle can be transferred and moved to several platforms. Thoughts?

**Comment by jamuhl** [comment]
where is the issue...a bundle file just needs to be loaded into i18next it's always an access to t function to access the translations, might be with some additional sugar depending on framework used with. There is nothing to do to use a file with jquery or react - important is only the defined keys and filenames.

that's why you can use eg. http://locize.com as a backend service.

**Comment by jamuhl** [comment]
Don't get me wrong...really open to improvements - but need to know more what you have on mind, eg. some sample code/text.

**Comment by ghost** [comment]
I think one way that would be a great demonstration of this ecosystem's true value is to provide an example which where a single i18next resource bundle is used in an iOS, android, and web application. In part, doing this would come with recommendations on how to include the language resource bundle into these projects. Ideally, these recommendations would be available on the i18next site documentation.

I opened an issue for the purpose of holding a forum on the idea and hopefully find useful suggestions on how to ensure this sort of demonstration and documentation is both useful and efficient.

Thought, perhaps planning this out is not the ideal approach. I will close this and submit a pull request. We can discuss the changes upon submission when there is a more concrete example.

**Comment by jamuhl** [comment]
sounds great....looking forward to the PR
