### ISSUE TITLE
Recommendation: API Example I/O

### ISSUE THREAD

**Issue by ghost** [i18next/i18next.com#14]
Currently the API documentation: https://github.com/i18next/i18next.com/blob/master/pages/docs/api/index.md 

I believe this documentation could be improved by including example input and example output for each API call. Each parameter argument could also include the argument's Type. Am I missing anything which could improve this documentation?

**Comment by jamuhl** [comment]
http://i18next.com/docs/api/ feel free to improve that page. not sure if that is of such importance...as most time you just need the init and t function which is described here http://i18next.com/translate/ in detail.
